name: test-on-commit

on:
  push:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get -y install liblzo2-dev liblzma-dev zlib1g-dev build-essential
      - run: | 
          wget https://dbmx.net/kyotocabinet/pkg/kyotocabinet-1.2.79.tar.gz
          tar -xvzf kyotocabinet-1.2.79.tar.gz && mv kyotocabinet-1.2.79 kyotocabinet && rm kyotocabinet-1.2.79.tar.gz
          cd kyotocabinet
          ./configure --enable-lzo --enable-lzma
          make
          sudo make install
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm test
